In [1]:
import numpy as np
import pandas as pd

In [3]:
ratings = pd.read_csv("data/train_ratings.csv")
books = pd.read_csv("data/books_final.csv")
users = pd.read_csv("data/users_preprocessed.csv")


In [21]:
data = ratings.merge(users, "left", 'user_id').merge(books, "left", 'isbn')

In [22]:
data.head()

user_id        isbn  rating   age   location_city location_state  \
0        8  0002005018       4  18.0  ontario_others        ontario   
1    67544  0002005018       7  30.0         toronto        ontario   
2   123629  0002005018       8  30.2        kingston        ontario   
3   200273  0002005018       8  18.0  ontario_others        ontario   
4   210926  0002005018       9  26.5          guelph        ontario   

  location_country  year_of_publication publisher language  ... new_language  \
0           canada               2001.0   Collins       en  ...           en   
1           canada               2001.0   Collins       en  ...           en   
2           canada               2001.0   Collins       en  ...           en   
3           canada               2001.0   Collins       en  ...           en   
4           canada               2001.0   Collins       en  ...           en   

  remove_country_code isfiction isenglish book_author_over3 book_author_over5  \
0           002005018         0         1            others            others   
1           002005018         0         1            others            others   
2           002005018         0         1            others            others   
3           002005018         0         1            others            others   
4           002005018         0         1            others            others   

  book_author_over50  book_author_over100  new_year publisher_small  
0             others               others         4          others  
1             others               others         4          others  
2             others               others         4          others  
3             others               others         4          others  
4             others               others         4          others  

[5 rows x 25 columns]

In [23]:
# data['rating>5'] = 
def tmp(x):
    if x <= 5:
        return 0
    elif x <= 8:
        return 1
    else:
        return 2
data['rating_group'] = data['rating'].map(tmp)

In [24]:
data = data.merge(data.groupby('user_id')['rating'].mean().rename('user_rating_mean').reset_index(), 'left', 'user_id')
data = data.merge(data.groupby('isbn')['rating'].mean().rename('book_rating_mean').reset_index(), 'left', 'isbn')

In [27]:
data = data.merge(data.groupby('user_id')['isbn'].count().rename('user_book_count').reset_index(), 'left', 'user_id')
data = data.merge(data.groupby('isbn')['user_id'].count().rename('book_user_count').reset_index(), 'left', 'isbn')


In [53]:
# new_language
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)
tmp = data.groupby(['rating', 'new_language'])['isbn'].agg(['count']).sort_index().unstack()
tmp.apply(lambda x: x/tmp.apply(lambda x: x.sum(skipna=True), axis=1), axis=0).mul(100)


count                                                  \
new_language        ar      bg        cp        cs        da        de   
rating                                                                   
1             0.007588     NaN       NaN       NaN       NaN  6.730404   
2                  NaN     NaN       NaN       NaN  0.007780  2.847363   
3                  NaN     NaN       NaN       NaN       NaN  2.931627   
4                  NaN     NaN       NaN  0.007911       NaN  2.903251   
5                  NaN     NaN       NaN       NaN  0.007121  3.838485   
6                  NaN     NaN       NaN  0.003973  0.007946  3.476361   
7                  NaN  0.0019       NaN  0.003800  0.001900  3.043429   
8             0.002732     NaN       NaN  0.002732       NaN  2.741204   
9                  NaN     NaN       NaN       NaN  0.004130  2.657883   
10                 NaN     NaN  0.002354       NaN  0.002354  2.469630   

                                                                           \
new_language        el         en        es        fa      fail        fi   
rating                                                                      
1                  NaN  89.756431  1.487215  0.007588  0.022763  0.015176   
2                  NaN  94.040766  1.836004       NaN  0.007780       NaN   
3                  NaN  94.088999  1.699771       NaN       NaN       NaN   
4                  NaN  94.114390  1.605886       NaN  0.007911  0.007911   
5                  NaN  91.568153  2.236149       NaN  0.021364  0.007121   
6             0.007946  92.050060  2.240763       NaN  0.011919  0.015892   
7             0.001900  92.769482  1.825677       NaN  0.011399  0.001900   
8             0.004097  93.718586  1.445039       NaN  0.024585  0.005463   
9             0.002065  94.322828  1.199868       NaN  0.018587       NaN   
10                 NaN  95.173745  0.856955  0.002354  0.016480       NaN   

                                                                          \
new_language        fr        he        hi        hr        hu        id   
rating                                                                     
1             1.487215  0.007588       NaN       NaN       NaN       NaN   
2             0.902443  0.007780  0.007780       NaN       NaN       NaN   
3             0.849885       NaN  0.019099       NaN       NaN       NaN   
4             0.925560       NaN  0.015822  0.007911       NaN       NaN   
5             1.659308       NaN       NaN       NaN       NaN       NaN   
6             1.640842       NaN  0.003973       NaN  0.003973       NaN   
7             1.713591       NaN  0.007599  0.003800  0.001900  0.001900   
8             1.561134  0.002732  0.008195  0.002732       NaN       NaN   
9             1.379538       NaN  0.002065       NaN  0.002065       NaN   
10            1.099444       NaN  0.002354       NaN  0.002354  0.002354   

                                                                      \
new_language      is        it        ja      ka        ko        ms   
rating                                                                 
1                NaN  0.288338       NaN     NaN       NaN  0.007588   
2                NaN  0.178933  0.015559     NaN       NaN  0.015559   
3                NaN  0.210084  0.038197     NaN       NaN  0.009549   
4                NaN  0.221501  0.023732     NaN       NaN  0.007911   
5                NaN  0.462897       NaN     NaN       NaN  0.028486   
6                NaN  0.294001  0.015892     NaN       NaN  0.007946   
7             0.0019  0.349557  0.028497  0.0019       NaN  0.011399   
8                NaN  0.259506  0.019122     NaN  0.001366  0.015024   
9                NaN  0.223039  0.030978     NaN       NaN  0.008261   
10               NaN  0.214239  0.035314     NaN  0.004709  0.011771   

                                                                          \
new_language       ngo        nl        no        

In [69]:
# category_high
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)
tmp = data.groupby(['rating', 'category_high'])['isbn'].agg(['count']).sort_index()
# tmp2 = tmp.apply(lambda x: x/tmp.apply(lambda x: x.sum(skipna=True), axis=1), axis=0).mul(100)
tmp


count
rating category_high              
1      abortion                  2
       abused wives              1
       actors                    4
       adolescence               5
       adultery                  7
...                            ...
10     true crime               94
       united states             2
       vampires                  3
       veterinarians             7
       world war, 1939-1945      1

[2848 rows x 1 columns]

In [74]:
from deepctr_torch.inputs import SparseFeat, DenseFeat, get_feature_names

ModuleNotFoundError: No module named 'deepctr_torch'

In [90]:
a = np.array([1,2,3,4,5])

In [94]:
import torch

In [99]:
a = torch.randn(5,3)
b = torch.randn(5,6)

In [100]:
a, b

(tensor([[-0.7056, -1.9473, -1.2119],
         [-0.2268,  0.3262,  0.7370],
         [ 0.9119,  0.3898,  0.7143],
         [ 0.6964,  0.4805,  0.3755],
         [ 0.9034, -1.3396, -0.8457]]),
 tensor([[-0.1195, -0.4674,  0.3581, -1.2222, -1.1913, -0.0114],
         [-0.4478, -1.3867, -0.1269,  1.0710, -0.4220,  1.0396],
         [ 0.2167, -1.1509,  0.2649, -0.6380, -0.1631, -0.8415],
         [ 0.2264, -1.3696, -0.0195,  0.7180, -0.3644,  0.3904],
         [-0.2681,  0.9235,  0.4348,  0.8560, -0.9574,  0.6808]]))

In [101]:
torch.cat([a,b], dim=1)

tensor([[-0.7056, -1.9473, -1.2119, -0.1195, -0.4674,  0.3581, -1.2222, -1.1913,
         -0.0114],
        [-0.2268,  0.3262,  0.7370, -0.4478, -1.3867, -0.1269,  1.0710, -0.4220,
          1.0396],
        [ 0.9119,  0.3898,  0.7143,  0.2167, -1.1509,  0.2649, -0.6380, -0.1631,
         -0.8415],
        [ 0.6964,  0.4805,  0.3755,  0.2264, -1.3696, -0.0195,  0.7180, -0.3644,
          0.3904],
        [ 0.9034, -1.3396, -0.8457, -0.2681,  0.9235,  0.4348,  0.8560, -0.9574,
          0.6808]])

In [109]:
np.delete(np.arange(10), np.array([1,2]))

array([0, 3, 4, 5, 6, 7, 8, 9])